### PR TITLE
Container refactor fixes + pattern editor refresh

### LINKED ISSUE #397: Pattern Editor: Removing non-stop control point throws error
Clicking a control point to remove it causes an error to be thrown. Upon further inspection, it looks like we're not handling the recalculated shape segments correctly. 

https://github.com/conveyal/datatools-ui/blob/a6cb68607877120d4c4a1f753355ccaa1026ac3d/lib/editor/util/map.js#L495-L504

`newSegment.coordinates` should not be spread in the above statement. Rather, it needs to be simply spliced in as an array of coordinates because the correct type of pattern coordinates is `Array<Coordinates>` (e.g., `[[[1, 0], [0, 1]], [[1, 1], [0, 0]]]`.

### PR DESCRIPTION
**Pull request by landonreed**
This PR addresses a few items discovered while working on some fixes for Pace Bus.

- fixes a few issues encountered with pattern editing (#395, #400, #399, fixes #397)
- fixes the editor lock overwrite functionality (also #395) and the redirect on login (#396)
- tweaks the layout of the pattern shape editor so that it's a bit more intuitive (see screengrab)
- replaces the direction icons for the pattern geometry with `leaflet-textpath` for better performance/legibility (see second screengrab)
- changes some components to `PureComponents` to prevent them from rendering as frequently (I'm not sure if this is effective in all the cases, so we may need to revisit some of the components, e.g. Sidebar).

image

image

### CODE REVIEW

**Comment by evansiroky** [comment]
The CI runs are failing due to unresolved flow type errors.  Please fix those.

File: lib/editor/selectors/index.js [hunk 1]
```diff
@@ -125,6 +128,20 @@ const getPresentControlPoints = (state: AppState) => {
   return state.editor.editSettings.present.controlPoints
 }
 export const getTripCounts = (state: AppState) => state.editor.data.tables.trip_counts
+export const getActivePatternStops = createSelector(
```
Comment (evansiroky) [inline lib/editor/selectors/index.js]: Please write a unit test for this selector.

File: lib/editor/selectors/index.js [hunk 2]
```diff
@@ -360,10 +381,10 @@ function getControlPointsFromShapePoints (shapePoints: Array<ShapePoint>) {
 function addPatternStopsToShapePoints (
   oldShapePoints: Array<ShapePoint>,
   patternStops: Array<PatternStop>,
-  stops: Array<any>, // TODO: use more exact type
+  activePatternStops: Array<GtfsStop>,
```
Comment (evansiroky) [inline lib/editor/selectors/index.js]: Would be fantastic to have a unit test for this function too.  Of course it'd be awesome to have unit tests for each possible scenario, but even a test that sent the oldShapePoints variable with a length being less than 2 is a good starting point as this big function has 0% coverage.

File: lib/editor/util/gtfs.js [hunk 3]
```diff
@@ -165,7 +165,7 @@ export const generateProps = (component: string, editorState: any): any => {
   }
 }
 
-export function getEntityBounds (entity: any, offset: number = 0.005): ?latLngBounds {
+export function getEntityBounds (entity: any, stops?: Array<GtfsStop>, offset: number = 0.005): ?latLngBounds {
```
Comment (evansiroky) [inline lib/editor/util/gtfs.js]: This could also use a very basic unit test.

File: lib/editor/util/map.js [hunk 4]
```diff
@@ -288,7 +288,7 @@ export async function recalculateShape ({
   index: number,
   newPoint?: LatLng,
   pattern: Pattern,
-  patternCoordinates: Coordinates,
+  patternCoordinates: Array<Coordinates>,
```
Comment (evansiroky) [inline lib/editor/util/map.js]: Another great candidate for adding tests.  Especially since there is already a file `lib/editor/util/__tests__/map.js_hold` with test cases for this exact function.

**Comment by evansiroky** [comment]
The "hide inactive segments" checkbox could be greyed out unless there are some currently active segments.  Otherwise it's a little confusing since it's hiding everything all segments.

**Comment by landonreed** [comment]
https://github.com/conveyal/datatools-ui/pull/401#issuecomment-458434242 is resolved with the [latest version of gtfs-lib](https://github.com/conveyal/gtfs-lib/releases/tag/v4.2.5).

**Comment by landonreed** [comment]
@evansiroky, I have finally addressed your comments here, but this PR doesn't add unit tests. I think it's a higher priority to get this merged in though at this point to avoid any more dust gathering.

**Comment by evansiroky** [comment]
https://github.com/conveyal/datatools-ui/pull/401#issuecomment-458434242 does not appear to be fixed while running datatools-server with gtfs-lib 4.2.5. Please see video posted in company slack.

File: lib/editor/util/__tests__/map.js [hunk 5]
```diff
@@ -56,23 +63,24 @@ describe('editor > util > map >', () => {
       makeTestCase({
         editType: 'update',
         index: 0,
-        mapzenResponeFile: './fixtures/mapzen-response-update-first-stop.json',
+        // https://
```
Comment (evansiroky) [inline lib/editor/util/__tests__/map.js]: please remove comment

File: lib/editor/util/__tests__/__snapshots__/map.js.snap [hunk 6]
```diff
@@ -0,0 +1,1244 @@
...
+      ],
+      Array [
+        -77.922112,
+        42.088844,
+      ],
+      Array [
+        -77.922135,
+        42.089099,
+      ],
+    ],
```
Comment (evansiroky) [inline lib/editor/util/__tests__/__snapshots__/map.js.snap]: The coordinates in this array don't go all the way to the new last stop. Is this the desired behavior?

This is what the coordinates look like before deleting the last stop:

Screen Shot 2019-04-02 at 5 28 57 PM

And here are those coordinates after:

Screen Shot 2019-04-02 at 5 29 33 PM

File: lib/editor/util/__tests__/__snapshots__/map.js.snap [hunk 7]
```diff
@@ -0,0 +1,1244 @@
...
+        -77.922974,
+        42.095657,
+      ],
+      Array [
+        -77.923104,
+        42.096481,
+      ],
+    ],
+  ],
+  "updatedControlPoints": Array [
```
Comment (evansiroky) [inline lib/editor/util/__tests__/__snapshots__/map.js.snap]: This snapshot makes no sense due to bad input data. The pattern coordinates are in NY while the control point coordinates are in CA.

**Comment by landonreed** [comment]
Yes, sorry about that. I was trying to adapt preexisting fixtures and that was a bad idea. I'll regenerate them from new input data.

File: lib/editor/util/__tests__/__snapshots__/map.js.snap [hunk 8]
```diff
@@ -834,96 +665,40 @@ Object {
...
-      ],
-      Array [
-        -77.922974,
-        42.095657,
-      ],
-      Array [
-        -77.923104,
-        42.096481,
+        -77.92187333106995,
+        42.08646327816015,
```
Comment (evansiroky) [inline lib/editor/util/__tests__/__snapshots__/map.js.snap]: This coordinate in the snapshot for `should update the first stop` seems out of place. This indicates that the shape goes backwards.

Here are the pattern coordinates and stops before the test:

Screen Shot 2019-04-03 at 2 53 02 PM
 
And after recalcuate shape is ran:

Screen Shot 2019-04-03 at 2 53 13 PM

The segment between the first and 2nd stop looks fine, but the shape doesn't continue to the last stop. Instead it goes backwards. You can't see if from that last picture, so here is a more zoomed in look:

Screen Shot 2019-04-03 at 3 04 43 PM

File: lib/editor/util/__tests__/__snapshots__/map.js.snap [hunk 9]
```diff
@@ -1030,76 +797,32 @@ Object {
   "coordinates": Array [
     Array [
       Array [
-        -77.922203,
-        42.086407,
+        -77.9230535030365,
+        42.096176462786296,
```
Comment (evansiroky) [inline lib/editor/util/__tests__/__snapshots__/map.js.snap]: The same odd thing in `should update the first stop` is now happening in reverse in the `should update the last stop`.

Before the test:

Screen Shot 2019-04-03 at 3 11 40 PM

After:

Screen Shot 2019-04-03 at 3 11 23 PM

Zoomed in the first point is now going backwards to some other point and going forward.

Screen Shot 2019-04-03 at 3 13 19 PM

File: lib/editor/util/__tests__/fixtures/test-control-points.json [hunk 10]
```diff
@@ -40,16 +38,12 @@
...
-  "defaultDwellTime": 0,
-  "timepoint": null,
-  "shapeDistTraveled": 691.729078104771,
-  "hidden": true
+  "stopId": "a9c9cd55-ca3f-4ce7-9a93-96f2f4eaf089"
 }, {
   "distance": 905.1384059344052,
   "id": "0cj3",
-  "permanent": true,
+  "pointType": 2,
```
Comment (evansiroky) [inline lib/editor/util/__tests__/fixtures/test-control-points.json]: This should probably be `1` since there is no stopId for this control point.

File: lib/editor/util/__tests__/__snapshots__/map.js.snap [hunk 11]
```diff
@@ -583,46 +448,22 @@ Object {
...
-      ],
-      Array [
-        -77.922196,
-        42.086498,
-      ],
-      Array [
-        -77.922173,
-        42.086498,
+        -77.9230535030365,
+        42.096176462786296,
```
Comment (evansiroky) [inline lib/editor/util/__tests__/__snapshots__/map.js.snap]: This snapshot for `should update a point in the middle of the control points` seems really off again.

Before:

Screen Shot 2019-04-03 at 4 41 44 PM

After:

Screen Shot 2019-04-03 at 4 41 35 PM

File: lib/editor/util/__tests__/__snapshots__/map.js.snap [hunk 12]
```diff
@@ -160,70 +125,30 @@ Object {
   "coordinates": Array [
     Array [
       Array [
-        -77.922135,
-        42.089099,
```
Comment (evansiroky) [inline lib/editor/util/__tests__/__snapshots__/map.js.snap]: The result of the `should delete the first stop` test implies that the last stop is deleted and the line is backwards!

Before:

Screen Shot 2019-04-03 at 5 06 01 PM

After:

Screen Shot 2019-04-03 at 5 05 52 PM

**Comment by landonreed** [comment]
Agh, you're right. Sorry about that. I'm going to add some log statements that actually print out geojson.io links to make this stuff a little easier to debug.
